version: 1.2
workflows:
 - name: Serratia_Preprocess
   subclass: WDL
   primaryDescriptorPath: /workflows/serratia_preprocess.wdl
   testParameterFiles:
    - empty.json
 - name: Fastqc_Aggregate
   subclass: WDL
   primaryDescriptorPath: /workflows/fastqc_aggregate.wdl
   testParameterFiles:
    - empty.json
 - name: Serratia_Assemble
   subclass: WDL
   primaryDescriptorPath: /workflows/serratia_assemble.wdl
   testParameterFiles:
    - empty.json
 - name: get_coverage
   subclass: WDL
   primaryDescriptorPath: /workflows/get_coverage.wdl
   testParameterFiles:
    - empty.json
 - name: Get_Coverage
   subclass: WDL
   primaryDescriptorPath: /workflows/get_coverage.wdl
   testParameterFiles:
    - empty.json